/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LocalizationStrings, AppLanguage } from './types';

export const LOCALIZATION_DATA: Record<AppLanguage, LocalizationStrings> = {
  EN: {
    brandName: "NABETAFOOD",
    slogan: "Warri's hottest food delivery • Freshly cooked daily • 15 - 45 min delivery",
    excellent: "Excellent",
    reviews: "reviews",
    whatsOnPlate: "WHAT'S IN YOUR PLATE",
    addMoreProteins: "Add More Proteins",
    proteinsSub: "Default proteins already included above. Add extras below.",
    changeSwallow: "Change Your Swallow",
    swallowSub: "Default swallow pre-selected. Change to your preference below.",
    quantity: "Quantity",
    itemTotal: "Item Total",
    addToCart: "Add to Cart",
    cartEmpty: "Your cart is empty. Explore our premium selection!",
    subtotal: "Subtotal",
    deliveryFee: "Delivery Fee",
    total: "Total",
    placeOrder: "Place Order & Pay",
    ratingText: "out of 5",
    loyaltyPoints: "Loyalty Points",
    pts: "pts",
    orderStatus: {
      placed: "Order Received",
      preparing: "Chef is Cooking",
      transit: "Rider in Transit",
      delivered: "Delivered Warm"
    },
    orderStatusDesc: {
      placed: "Your order has been logged into our Real-time Firebase Database.",
      preparing: "Our master chefs are preparing your delicious culinary selection.",
      transit: "Your hot meal is out for delivery. Track the rider location on the live map.",
      delivered: "Enjoy your rich delicacies! Share your rating on NABETAFOOD."
    },
    rewardsTitle: "NABETAFOOD Gold Club",
    rewardsTier: "Loyalty Reward Status",
    darkMode: "Dark Mode",
    notifications: "Notifications",
    secureCheckout: "Secure Payment Center",
    cardName: "Cardholder Name",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    payWithCard: "Authenticate secure transfer of",
    orderTracking: "Real-time Order Tracker",
    estDelivery: "Est. arrival: 15 mins",
    deliveredSuccess: "Order delivered successfully!",
    referralTitle: "Refer a Friend, Earn Points",
    referralDesc: "Share the authentic taste of Warri. You both get 200 NABETAFOOD bonus points!"
  },
  YO: {
    brandName: "NABETAFOOD",
    slogan: "Oúnjẹ gígbóná ní Warri • Síse tuntun lójoojúmó • 15 - 45 iṣẹ́jú",
    excellent: "Léwu gan-an",
    reviews: "àpajù",
    whatsOnPlate: "KÍN LÓ WÀ NÍNÚ ÀWO RE",
    addMoreProteins: "Fi Eran Tàbí Ẹja Kún Un",
    proteinsSub: "Àwọn èròja tó wà lókè ti wà níbẹ̀ tẹ́lẹ̀. Fi àfikún kún un nísàlẹ̀.",
    changeSwallow: "Yí Òkèlè Rẹ Padà",
    swallowSub: "A ti yan òkèlè tẹ́lẹ̀ fún ọ. Yí padà sí èyí tí o fẹ́ nísàlẹ̀.",
    quantity: "Iye",
    itemTotal: "Àpapọ̀ Oúnjẹ",
    addToCart: "Fi Sínú Apẹ̀rẹ̀",
    cartEmpty: "Apẹ̀rẹ̀ rẹ ti ṣofo. Ṣàwárí àwọn oúnjẹ adùn wa!",
    subtotal: "Apapọ́ Kekere",
    deliveryFee: "Owó Ìfiránṣẹ́",
    total: "Gbogbo Rẹ̀",
    placeOrder: "Fi Àṣẹ Rà & Sànwó",
    ratingText: "nínú 5",
    loyaltyPoints: "Àwọn Ohun Ìṣírí",
    pts: "pisin",
    orderStatus: {
      placed: "A Ti Gba Àṣẹ",
      preparing: "Olóúnjẹ Ń Sè Ẹ́",
      transit: "Awọ̀n Ìfiránṣẹ́ Ti Gbéra",
      delivered: "A ti Gbé e Sọ̀kalẹ̀"
    },
    orderStatusDesc: {
      placed: "A ti kọ àṣẹ rẹ sínú Àdatabase Firebase gidi wa.",
      preparing: "Àwọn olóúnjẹ wa ń múra culinary rẹ títí yóò fi gboná.",
      transit: "Oúnjẹ rẹ tí gbgbéra adùn. Tọpinpin olùgbéṣẹ́ lórí maapu.",
      delivered: "Gbádùn oúnjẹ rẹ adùn! Sọ̀rọ̀ nípa rẹ̀ lórí NABETAFOOD."
    },
    rewardsTitle: "NABETAFOOD Club Wúrà",
    rewardsTier: "Ipele Ohun Ìṣírí",
    darkMode: "Ipo Òkùnkùn",
    notifications: "Ìfitonilétí",
    secureCheckout: "Ibi Ìsànwó Aláàbò",
    cardName: "Orúkọ Olówó Kaadi",
    cardNumber: "Nọ́mbà Kaadi",
    expiryDate: "Ọjọ́ Tó Máa Kú",
    cvv: "CVV",
    payWithCard: "Fọwọ́sí ìfiránṣẹ́ owó ti",
    orderTracking: "Tọpinpin Àṣẹ Rẹ",
    estDelivery: "Akókò: iṣẹ́jú 15",
    deliveredSuccess: "Oúnjẹ dé bẹ́ẹ̀ lọ́wọ́lọ́wọ́!",
    referralTitle: "Mú Ọ̀rẹ́ Wá, Gba Ohun Ìṣírí",
    referralDesc: "Sọ̀rọ̀ nípa oúnjẹ Warri. Ẹ̀yin méjèèjì yóò gba igba ohun ìṣírí!"
  },
  IG: {
    brandName: "NABETAFOOD",
    slogan: "Nri kacha ekpo ọkụ na Warri • Isi ọhụrụ kwa ụbọchị • Nji 15 - 45 min",
    excellent: "Ọmarịcha",
    reviews: "ndị nyocha",
    whatsOnPlate: "GỊNỊ DỊ NA EFERE GỊ",
    addMoreProteins: "Tinye Anụ ma ọ bụ Azụ",
    proteinsSub: "Ihe protein ndị dị n'elu adịla n'ime mbụ. Tinye ndị ọzọ n'okpuru.",
    changeSwallow: "Gbanwee Ụdị Nri Ọkụ Gị",
    swallowSub: "A họrọla nri ọkụ ndabere maka gị. Gbanwee ka ọ masịrị gị.",
    quantity: "Ọnụ ọgụgụ",
    itemTotal: "Ngụkọta Ihe",
    addToCart: "Tinye na Nkata",
    cartEmpty: "Nkata gị tọgbọrọ nkịtị. Nyochaa nri pụrụ iche anyị!",
    subtotal: "Ngụkọta",
    deliveryFee: "Ego mbufe",
    total: "Ego niile",
    placeOrder: "Tụọ Nri & Hụọ Ego",
    ratingText: "n'ime 5",
    loyaltyPoints: "Ego Ahụmịhe",
    pts: "points",
    orderStatus: {
      placed: "Anabatara Atụmatụ gị",
      preparing: "Onye na-esi nri na-arụ ọrụ",
      transit: "Ọkwọ ụgbọ ala na-abịa",
      delivered: "Ebutere ya nke ọma"
    },
    orderStatusDesc: {
      placed: "E tinyela atụmatụ nri gị na nchekwa data Firebase anyị.",
      preparing: "Ndị kachasị isi nri anyị na-akwadebe nri pụrụ iche gị.",
      transit: "Nri gị na-ekpo ọkụ amalitela njem. Chọpụta ebe ọkwọ ụgbọala nọ na maapụ.",
      delivered: "Rielgị nri ọma! Kọọrọ anyị otú ọ dị na NABETAFOOD."
    },
    rewardsTitle: "NABETAFOOD Gold Club",
    rewardsTier: "Igo nkwalite",
    darkMode: "Ụdị Ọchịchịrị",
    notifications: "Ozi Ọkụ",
    secureCheckout: "Ibe Ịkwụ Ụgwọ Dị Nchebe",
    cardName: "Aha Onye Nwere Kaadị",
    cardNumber: "Nọmba Kaadị",
    expiryDate: "Ụbọchị mmebi",
    cvv: "CVV",
    payWithCard: "Kwenye nkwụnye ego nke",
    orderTracking: "Ndetu ebe nri gị dị",
    estDelivery: "Oge fọrọ: nkeji 15",
    deliveredSuccess: "Ebutere nri ahụ nke ọma!",
    referralTitle: "Kpọọ enyi, Nweta ego ahụmịhe",
    referralDesc: "Kọọrọ ndị ọzọ banyere nri Warri. Unu abụọ ga-enweta 200 points!"
  },
  HA: {
    brandName: "NABETAFOOD",
    slogan: "Abinci mafi zafi a Warri • Sabon girki kullum • Isarwa cikin minti 15-45",
    excellent: "Madalla",
    reviews: "bita",
    whatsOnPlate: "MENE NE A CIKIN FARANTIN KU",
    addMoreProteins: "Ƙara Naman ko Kifi",
    proteinsSub: "Abubuwan da ke sama suna ciki riga. Ƙara ƙarin abubuwa a ƙasa.",
    changeSwallow: "Canza Haɗin Hadiya",
    swallowSub: "An rigaya an zaɓi hadiya ta asali. Sauya zuwa abin da kuke so a ƙasa.",
    quantity: "Yawa",
    itemTotal: "Jimillar Abinci",
    addToCart: "Ƙara zuwa Rago",
    cartEmpty: "Ragon ku babu komai. Bincika ingantaccen abincinmu!",
    subtotal: "Jimillar Farko",
    deliveryFee: "Kudin Isarwa",
    total: "Jimilla",
    placeOrder: "Yanke Shawara & Biya",
    ratingText: "cikin 5",
    loyaltyPoints: "Abubuwan Aminci",
    pts: "baki",
    orderStatus: {
      placed: "An Karɓi Umarni",
      preparing: "Mai dafa abinci yana nan",
      transit: "Mai Isarwa yana Hanya",
      delivered: "An Isar Lafiya"
    },
    orderStatusDesc: {
      placed: "An shigar da umarnin ku a cikin rumbun adana bayanan mu na Firebase.",
      preparing: "Mafi kwararrun masu dafa abincinmu suna shirya muku abinci.",
      transit: "Abincin ku yana hanya yana da dumi. Dubi inda yake a taswira.",
      delivered: "Kuji daɗin abincinku! Ku ba da ra'ayi a NABETAFOOD."
    },
    rewardsTitle: "NABETAFOOD Gold Club",
    rewardsTier: "Matsayin Aminci",
    darkMode: "Yanayin Duhu",
    notifications: "Sanarwa",
    secureCheckout: "Hanyar Biya Amintacciya",
    cardName: "Sunan Kan Kati",
    cardNumber: "Lambar Kati",
    expiryDate: "Ranar Karewa",
    cvv: "CVV",
    payWithCard: "Amince da tura kudi na",
    orderTracking: "Binciken inda Abinci Yake",
    estDelivery: "Lokaci: minti 15",
    deliveredSuccess: "An kawo abincin lafiya lau!",
    referralTitle: "Gayyaci Aboki, Sami Lada",
    referralDesc: "Yi magana game da dandanon Warri. Ku duka zaku sami maki bonus 200!"
  },
  FR: {
    brandName: "NABETAFOOD",
    slogan: "Livraison des plats les plus chauds de Warri • Cuisiné frais • 15 - 45 min",
    excellent: "Excellent",
    reviews: "avis",
    whatsOnPlate: "QU'Y A-T-IL DANS VOTRE ASSIETTE",
    addMoreProteins: "Ajouter des Protéines",
    proteinsSub: "Protéines par défaut incluses ci-dessus. Ajoutez des extras ci-dessous.",
    changeSwallow: "Changer d'Accompagnement (Swallow)",
    swallowSub: "Accompagnement par défaut pré-sélectionné. Modifiez selon vos préférences.",
    quantity: "Quantité",
    itemTotal: "Total de l'article",
    addToCart: "Ajouter au Panier",
    cartEmpty: "Votre panier est vide. Découvrez notre sélection premium !",
    subtotal: "Sous-total",
    deliveryFee: "Frais de livraison",
    total: "Total",
    placeOrder: "Passer Commande & Payer",
    ratingText: "sur 5",
    loyaltyPoints: "Points de Fidélité",
    pts: "pts",
    orderStatus: {
      placed: "Commande Reçue",
      preparing: "Chef en Cuisine",
      transit: "Coursier en Route",
      delivered: "Livré Chaud"
    },
    orderStatusDesc: {
      placed: "Votre commande est enregistrée dans notre Base de Données Firebase en temps réel.",
      preparing: "Nos chefs de cuisine préparent votre délice gastronomique.",
      transit: "Votre repas chaud est en route. Suivez le coursier en temps réel sur la carte.",
      delivered: "Bon appétit ! Partagez votre expérience sur NABETAFOOD."
    },
    rewardsTitle: "Club NABETAFOOD Or",
    rewardsTier: "Statut du Programme Fidélité",
    darkMode: "Mode Sombre",
    notifications: "Notifications",
    secureCheckout: "Centre de Paiement Sécurisé",
    cardName: "Nom sur la Carte",
    cardNumber: "Numéro de Carte",
    expiryDate: "Date d'Expiration",
    cvv: "Cryptogramme (CVV)",
    payWithCard: "Sécuriser le transfert de",
    orderTracking: "Suivi en Temps Réel",
    estDelivery: "Arrivée estimée: 15 mins",
    deliveredSuccess: "Commande livrée avec succès !",
    referralTitle: "Parrainez des Amis, Gagnez des Points",
    referralDesc: "Partagez la cuisine authentique de Warri. Gagnez chacun 200 points !"
  }
};
